default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
development:
  <<: *default
  host: localhost
  user: postgres
  password: changeme
  database: academy_db

# test:
#   <<: *default
#   database: test_academy_db
# production:
#   <<: *default
#   database: prod_academy_db
